spring:
  redis:
    host: 127.0.0.1
    port: 8008
    password: abc123456
    # 默认的实现方式，需要手动配置对应的参数
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
